import { chromium } from 'playwright';
import fs from 'fs';
const SP = 'C:/Users/nli0490/AppData/Local/Temp/claude/C--Users-nli0490-Claude/ffd95950-679d-45b8-a877-704ff4ac7e9a/scratchpad/';
const JS = fs.readFileSync('C:/Users/nli0490/Claude/Aroidpedia/docs/footer.js', 'utf8');
const b = await chromium.launch({ channel: 'chrome', headless: true });
const p = await b.newPage({ viewport: { width: 1500, height: 1100 } });
await p.route('**/footer.js*', r => r.fulfill({ body: JS, contentType: 'application/javascript', headers: { 'access-control-allow-origin': '*' } }));
await p.goto('https://www.aroidpedia.com/alocasia', { waitUntil: 'networkidle', timeout: 120000 });
await p.waitForTimeout(13000);
console.log('stamp:', await p.evaluate(() => document.querySelector('.apgm').getAttribute('data-apgm-version')));
console.log('Borneo leader:', await p.evaluate(() => {
  const lines = [...document.querySelectorAll('.apgm-maplead')];
  const lbls = [...document.querySelectorAll('.apgm-maplabel')];
  const i = lbls.findIndex(t => t.textContent === 'Borneo');
  const l = lines[i];
  return l ? 'x1=' + l.getAttribute('x1') + ' y1=' + l.getAttribute('y1') + ' x2=' + l.getAttribute('x2') + ' y2=' + l.getAttribute('y2') : '?';
}));
const svgH = await p.$('.apgm svg');
await svgH.scrollIntoViewIfNeeded();
const view = async v => { await p.evaluate(vv => { Array.from(document.querySelectorAll('.apgm [data-view]')).find(x => x.dataset.view === vv).click(); }, v); await p.waitForTimeout(800); };
await view('regions');
await svgH.screenshot({ path: SP + 'v26-regions.png', animations: 'disabled' });
await view('countries');
await svgH.screenshot({ path: SP + 'v26-countries.png', animations: 'disabled' });
await view('continents');
await svgH.screenshot({ path: SP + 'v26-continents.png', animations: 'disabled' });
console.log('done');
await b.close();
